# Generated by Django 5.0 on 2024-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('excert', models.CharField(max_length=250, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='about-me', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'информацию',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.AlterModelOptions(
            name='contentbanner',
            options={'verbose_name': 'контент', 'verbose_name_plural': 'Баннер'},
        ),
    ]
