# Generated by Django 5.0 on 2024-01-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPages', '0004_aboutme_alter_contentbanner_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='excert',
            new_name='expert',
        ),
    ]
