# Generated by Django 5.0 on 2024-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatenumber',
            name='number',
            field=models.IntegerField(default=380, verbose_name='Число'),
        ),
    ]
