# Generated by Django 5.0 on 2024-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponse', '0003_alter_generatenumber_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedate',
            name='status',
            field=models.BooleanField(blank=True, default=True, help_text='Да (Активный) / Нет (Не активный)', null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='generatenumber',
            name='number',
            field=models.IntegerField(default=540, verbose_name='Число'),
        ),
    ]
