# Generated by Django 5.0 on 2024-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResponse', '0004_alter_generatedate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatenumber',
            name='number',
            field=models.IntegerField(default=191, verbose_name='Число'),
        ),
    ]
