# Generated by Django 5.0 on 2024-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPublication', '0002_alter_pubnews_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubnews',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
